plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false


gems:
  - jekyll-sitemap
  

whitelist:
  - jekyll-sitemap


permalink: /:title

collection:
  - essay
  - work